# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 372)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/atom_colours.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        self.table_view.setObjectName("table_view")
        self.gridLayout.addWidget(self.table_view, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scan_button = QtWidgets.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scan_button.setIcon(icon1)
        self.scan_button.setObjectName("scan_button")
        self.horizontalLayout.addWidget(self.scan_button)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon2)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.passive_button = QtWidgets.QPushButton(self.frame)
        self.passive_button.setObjectName("passive_button")
        self.horizontalLayout.addWidget(self.passive_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.debug_button = QtWidgets.QPushButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/question.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.debug_button.setIcon(icon3)
        self.debug_button.setObjectName("debug_button")
        self.horizontalLayout_2.addWidget(self.debug_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.interface_box = QtWidgets.QComboBox(self.frame)
        self.interface_box.setObjectName("interface_box")
        self.horizontalLayout_2.addWidget(self.interface_box)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_options = QtWidgets.QMenu(self.menubar)
        self.menu_options.setObjectName("menu_options")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_start = QtWidgets.QAction(MainWindow)
        self.action_start.setObjectName("action_start")
        self.action_debug = QtWidgets.QAction(MainWindow)
        self.action_debug.setObjectName("action_debug")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu_file.addAction(self.actionSave)
        self.menu_help.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_options.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scan My LAN"))
        self.scan_button.setText(_translate("MainWindow", "Scan"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.passive_button.setText(_translate("MainWindow", "Passive"))
        self.debug_button.setText(_translate("MainWindow", "Debug"))
        self.menu_file.setTitle(_translate("MainWindow", "Fi&le"))
        self.menu_options.setTitle(_translate("MainWindow", "Options"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.action_start.setText(_translate("MainWindow", "Start"))
        self.action_start.setToolTip(_translate("MainWindow", "Start"))
        self.action_debug.setText(_translate("MainWindow", "Debug"))
        self.action_debug.setToolTip(_translate("MainWindow", "Various debugging stuff"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import scanmylan_resources_rc
